// <auto-generated />
using System;
using ConferenceRoomBooking.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceRoomBooking.Data.Migrations
{
    [DbContext(typeof(ConferenceRoomBookingContext))]
    [Migration("20260708132701_UpdatedTables")]
    partial class UpdatedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConferenceRoomId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DurationHours")
                        .HasColumnType("time");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceRoomId");

                    b.ToTable("BookingEntity", (string)null);
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.BookingServiceEntity", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionalServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId", "OptionalServiceId");

                    b.HasIndex("OptionalServiceId");

                    b.ToTable("BookingServiceEntity", (string)null);
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.ConferenceRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseHourPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ConferenceRoomEntity", (string)null);
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.OptionalServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ServicePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OptionalServiceEntity", (string)null);
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.RoomServiceEntity", b =>
                {
                    b.Property<Guid>("ConferenceRoomId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionalServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConferenceRoomId", "OptionalServiceId");

                    b.HasIndex("OptionalServiceId");

                    b.ToTable("RoomServiceEntity", (string)null);
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.BookingEntity", b =>
                {
                    b.HasOne("ConferenceRoomBooking.Domain.Entities.ConferenceRoomEntity", "ConferenceRoomEntity")
                        .WithMany("BookingEntitys")
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoomEntity");
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.BookingServiceEntity", b =>
                {
                    b.HasOne("ConferenceRoomBooking.Domain.Entities.BookingEntity", "BookingEntity")
                        .WithMany("BookingServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRoomBooking.Domain.Entities.OptionalServiceEntity", "OptionalServiceEntity")
                        .WithMany("BookingServices")
                        .HasForeignKey("OptionalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingEntity");

                    b.Navigation("OptionalServiceEntity");
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.RoomServiceEntity", b =>
                {
                    b.HasOne("ConferenceRoomBooking.Domain.Entities.ConferenceRoomEntity", "ConferenceRoom")
                        .WithMany("RoomServices")
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRoomBooking.Domain.Entities.OptionalServiceEntity", "OptionalService")
                        .WithMany("RoomServices")
                        .HasForeignKey("OptionalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");

                    b.Navigation("OptionalService");
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.BookingEntity", b =>
                {
                    b.Navigation("BookingServices");
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.ConferenceRoomEntity", b =>
                {
                    b.Navigation("BookingEntitys");

                    b.Navigation("RoomServices");
                });

            modelBuilder.Entity("ConferenceRoomBooking.Domain.Entities.OptionalServiceEntity", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("RoomServices");
                });
#pragma warning restore 612, 618
        }
    }
}
